package UIpackage;


import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import Driverclass.Labassign;
import Driverclass.Viewstudent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Lab_UI extends javax.swing.JFrame {
    
    
     Connection connection = null;
    PreparedStatement pst = null;
    ResultSet result = null;
     String sub_id;
        String intake;
        String timeslot ;
        String addr ;
        String gen ;
        String nic ;
        String email; 
        String cnum ;

    /**
    
     */
    public Lab_UI() {
        initComponents();
            
        view2();
        
    }
    
     public void view2(){
        
        Connection connection2;
        PreparedStatement pst2;
        ResultSet result2;
          
             String sql="SELECT * FROM ROOT.SUBJECT";
try{
connection2 = (Connection) DriverManager.getConnection("jdbc:derby://localhost:1527/nsbm2","root","root");
pst2=(PreparedStatement) connection2.prepareStatement(sql);
result2=pst2.executeQuery();
DefaultListModel model = new DefaultListModel();
if(result2.next())
{
JOptionPane.showMessageDialog(null,"Logged In Successfully");
        int row = 0;

    while((result2!=null) && (result2.next())){
        
        selecsub.addItem(result2.getString("SUBJECT_NAME"));
        
        
        
        
    }
    
    result2.close();
 
}
else
{
JOptionPane.showMessageDialog(null, "erroe");
}
}
catch(SQLException | HeadlessException ex)
{
JOptionPane.showMessageDialog(null,ex);
}
     }
     
      public void getInstructors(){
        
        Connection connection2;
        PreparedStatement pst2;
        ResultSet result2;
        sub_id = selecsub.getSelectedItem().toString();
        intake = intakebox.getSelectedItem().toString();
          
             String sql="SELECT * FROM ROOT.INSTRUCTOR WHERE SUBJECT = ? ";
try{
connection2 = (Connection) DriverManager.getConnection("jdbc:derby://localhost:1527/nsbm2","root","root");
pst2=(PreparedStatement) connection2.prepareStatement(sql);
pst2.setString(1, sub_id);
result2=pst2.executeQuery();
if(result2.next())
{
JOptionPane.showMessageDialog(null,"Logged In Successfully");
        

    do{
        
        selecins.addItem(result2.getString("INSTRUCTOR_NAME"));
        
        
        
        
    }while((result2!=null) && (result2.next()));
    
    result2.close();
 
}
else
{
JOptionPane.showMessageDialog(null, "erroe");
}
}
catch(SQLException | HeadlessException ex)
{
JOptionPane.showMessageDialog(null,ex);
}
     }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        labnum = new javax.swing.JComboBox<>();
        subjectlable = new javax.swing.JLabel();
        subjectlable1 = new javax.swing.JLabel();
        intakebox = new javax.swing.JComboBox<>();
        subjectlable2 = new javax.swing.JLabel();
        selecsub = new javax.swing.JComboBox<>();
        subjectlable3 = new javax.swing.JLabel();
        selecins = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        day = new javax.swing.JComboBox<>();
        subjectlable5 = new javax.swing.JLabel();
        subjectlable6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 775));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Assign");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(740, 670, 140, 40);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(160, 670, 130, 39);

        labnum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lab A", "Lab B", "Lab C" }));
        getContentPane().add(labnum);
        labnum.setBounds(350, 430, 180, 30);

        subjectlable.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        subjectlable.setForeground(new java.awt.Color(255, 255, 255));
        subjectlable.setText("Availability");
        getContentPane().add(subjectlable);
        subjectlable.setBounds(580, 360, 190, 60);

        subjectlable1.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        subjectlable1.setForeground(new java.awt.Color(255, 255, 255));
        subjectlable1.setText("Select Intake");
        getContentPane().add(subjectlable1);
        subjectlable1.setBounds(120, 190, 190, 60);

        intakebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "February ", "July" }));
        getContentPane().add(intakebox);
        intakebox.setBounds(320, 210, 180, 30);

        subjectlable2.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        subjectlable2.setForeground(new java.awt.Color(255, 255, 255));
        subjectlable2.setText("Select Subject");
        getContentPane().add(subjectlable2);
        subjectlable2.setBounds(120, 130, 190, 60);

        getContentPane().add(selecsub);
        selecsub.setBounds(320, 142, 180, 30);

        subjectlable3.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        subjectlable3.setForeground(new java.awt.Color(255, 255, 255));
        subjectlable3.setText("Select Instructor");
        getContentPane().add(subjectlable3);
        subjectlable3.setBounds(140, 360, 190, 60);

        getContentPane().add(selecins);
        selecins.setBounds(130, 430, 180, 30);

        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(570, 430, 140, 180);

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        getContentPane().add(day);
        day.setBounds(130, 540, 180, 30);

        subjectlable5.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        subjectlable5.setForeground(new java.awt.Color(255, 255, 255));
        subjectlable5.setText("Select Lab");
        getContentPane().add(subjectlable5);
        subjectlable5.setBounds(380, 360, 190, 60);

        subjectlable6.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        subjectlable6.setForeground(new java.awt.Color(255, 255, 255));
        subjectlable6.setText("Select Day");
        getContentPane().add(subjectlable6);
        subjectlable6.setBounds(160, 470, 190, 60);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(470, 250, 90, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Check Availability");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(370, 530, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Take home Assignment\\New folder\\nsbm\\labs.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        String instructor = selecins.getSelectedItem().toString();
        String lab = labnum.getSelectedItem().toString();
        String day1 = day.getSelectedItem().toString();
        
        Labassign lab2 = new Labassign();
        lab2.save(lab, day1, timeslot, sub_id, instructor, intake);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        this.getInstructors();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String lab = labnum.getSelectedItem().toString();
        String day1 = day.getSelectedItem().toString();
        DefaultListModel model = new DefaultListModel();
        
        Labassign laba = new Labassign();
        
        List<String> ls = laba.checkLab(lab, day1);
        for (int i = 0; i < ls.size(); i++)
{
    model.addElement(ls.get(i));
}
list1.setModel(model);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
        // TODO add your handling code here:
        timeslot = list1.getSelectedValue();
    }//GEN-LAST:event_list1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Staffmenu und = new Staffmenu();
        und.setVisible(true);
        und.setSize(1044,825);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Lab_UI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> day;
    private javax.swing.JComboBox<String> intakebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> labnum;
    private javax.swing.JList<String> list1;
    private javax.swing.JComboBox<String> selecins;
    private javax.swing.JComboBox<String> selecsub;
    private javax.swing.JLabel subjectlable;
    private javax.swing.JLabel subjectlable1;
    private javax.swing.JLabel subjectlable2;
    private javax.swing.JLabel subjectlable3;
    private javax.swing.JLabel subjectlable5;
    private javax.swing.JLabel subjectlable6;
    // End of variables declaration//GEN-END:variables
}
