package nsbm;


import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Lectures_UI extends javax.swing.JFrame {

    /**
     * Creates new form Course_UI
     */
    public Lectures_UI() {
        initComponents();
        view2();
    }
    
    
    public void view2(){
        
        Connection connection2;
        PreparedStatement pst2;
        ResultSet result2;
          
             String sql="SELECT * FROM ROOT.SUBJECT";
try{
connection2 = (Connection) DriverManager.getConnection("jdbc:derby://localhost:1527/nsbm2","root","root");
pst2=(PreparedStatement) connection2.prepareStatement(sql);
result2=pst2.executeQuery();
DefaultListModel model = new DefaultListModel();
if(result2.next())
{
JOptionPane.showMessageDialog(null,"Logged In Successfully");
        int row = 0;

    do{
        
        selecsub.addItem(result2.getString("SUBJECT_NAME"));
        
        
        
        
    }while((result2.next()));
    
    result2.close();
 
}
else
{
JOptionPane.showMessageDialog(null, "erroe");
}
}
catch(SQLException | HeadlessException ex)
{
JOptionPane.showMessageDialog(null,ex);
}
     
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sName = new javax.swing.JTextField();
        sAddress = new javax.swing.JTextField();
        s_email = new javax.swing.JTextField();
        staff_id = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        s_NIC = new javax.swing.JTextField();
        subjectlable = new javax.swing.JLabel();
        selecsub = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 775));
        getContentPane().setLayout(null);
        getContentPane().add(sName);
        sName.setBounds(410, 270, 400, 30);
        getContentPane().add(sAddress);
        sAddress.setBounds(410, 340, 400, 60);
        getContentPane().add(s_email);
        s_email.setBounds(410, 520, 390, 30);

        staff_id.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getContentPane().add(staff_id);
        staff_id.setBounds(410, 190, 400, 30);

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture", "Instructor" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type);
        type.setBounds(410, 120, 140, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(720, 640, 150, 40);
        getContentPane().add(s_NIC);
        s_NIC.setBounds(410, 440, 200, 40);

        subjectlable.setFont(new java.awt.Font("Lato", 0, 22)); // NOI18N
        subjectlable.setForeground(new java.awt.Color(255, 255, 255));
        subjectlable.setText("Select Subject");
        getContentPane().add(subjectlable);
        subjectlable.setBounds(140, 600, 190, 50);

        getContentPane().add(selecsub);
        selecsub.setBounds(410, 610, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Take home Assignment\\New folder\\nsbm\\academic staff.png")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1024, 775));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 775);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String staff_id1 = staff_id.getText();
        String sName1 = sName.getText();
        String address1 = sAddress.getText();
        String nic1 = s_NIC.getText();
        String email1 = s_email.getText();
        String type1 = type.getSelectedItem().toString();
        String subject = selecsub.getSelectedItem().toString();
        Academicstaff staff1 = new Academicstaff(staff_id1,sName1,address1,nic1,email1,subject);
        String lec = "Lecture";

        
        if (type1.equals(lec)){
            staff1.lectureSave();
           }
        else 
            {staff1.instructorSave();}
                
        
        
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lectures_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField sAddress;
    private javax.swing.JTextField sName;
    private javax.swing.JTextField s_NIC;
    private javax.swing.JTextField s_email;
    private javax.swing.JComboBox<String> selecsub;
    private javax.swing.JTextField staff_id;
    private javax.swing.JLabel subjectlable;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
